# Generated by Django 3.2.7 on 2022-01-09 11:11

from django.db import migrations, models
import services.models_services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MaleTemplate',
            fields=[
                ('id', models.CharField(default=services.models_services.pkgen, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=1024, verbose_name='Название шаблона')),
                ('template_path', models.TextField(help_text='Нужно внести путь к шаблону. Пример:"mailer/mail_templates/hello.html"', verbose_name='Путь к шаблону')),
                ('status', models.CharField(choices=[('ON', 'Активен'), ('OFF', 'В архиве')], max_length=5, verbose_name='Статус')),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
                'db_table': 'male_templates',
            },
        ),
        migrations.AddIndex(
            model_name='maletemplate',
            index=models.Index(fields=['title'], name='male_templa_title_3b68f0_idx'),
        ),
    ]
