# Generated by Django 3.2.7 on 2022-01-09 12:48

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager
import services.models_services


class Migration(migrations.Migration):

    dependencies = [
        ('subscribe', '0002_auto_20220109_1159'),
        ('mailer', '0003_auto_20220109_1159'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.CharField(default=services.models_services.pkgen, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('send_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('CREATE', 'Создана'), ('SENDING', 'Отправлена'), ('RECEIVED', 'Получена')], default='CREATE', max_length=10, verbose_name='Статус')),
                ('subscribers', models.ManyToManyField(to='subscribe.Subscriber', verbose_name='Подписчики')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mailings', to='mailer.mailtemplate', verbose_name='Шаблон')),
            ],
            options={
                'verbose_name': 'Рассылка',
                'verbose_name_plural': 'Рассылки',
            },
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
    ]
