# Generated by Django 3.2.7 on 2022-01-09 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailer', '0005_mailtemplate_mail_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailtemplate',
            name='mail_type',
            field=models.IntegerField(choices=[(1, 'Birthday'), (2, 'Offers')], default=1, verbose_name='Тип'),
        ),
    ]
