# Generated by Django 3.2.7 on 2022-01-07 16:41

from django.db import migrations, models
import services.models_services


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.CharField(default=services.models_services.pkgen, max_length=10, primary_key=True, serialize=False, unique=True)),
                ('first_name', models.CharField(max_length=512, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=512, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email адрес')),
                ('birthday', models.DateField(blank=True, null=True, verbose_name='День рождения')),
            ],
            options={
                'verbose_name': 'Подписчик',
                'verbose_name_plural': 'Подписчики',
                'db_table': 'subscriber',
            },
        ),
        migrations.AddIndex(
            model_name='subscriber',
            index=models.Index(fields=['email'], name='subscriber_email_81c3c5_idx'),
        ),
    ]
